python run_sweep.py sweeps/dambreak/obstacleTypeequilateralBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypeequilateralBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypeequilateralBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypetriangleBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypetriangleBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypetriangleBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypecircleBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypecircleBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypecircleBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypeellipsoidBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypeellipsoidBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypeellipsoidBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypesquareBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypesquareBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypesquareBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTyperoundedBoxBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTyperoundedBoxBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTyperoundedBoxBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypehexagonBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypehexagonBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypehexagonBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypestarBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypestarBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypestarBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypewallBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypewallBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypewallBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypeequilateralBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypeequilateralBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypeequilateralBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypetriangleBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypetriangleBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypetriangleBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypecircleBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypecircleBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypecircleBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypeellipsoidBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypeellipsoidBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypeellipsoidBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypesquareBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypesquareBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypesquareBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTyperoundedBoxBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTyperoundedBoxBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTyperoundedBoxBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypehexagonBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypehexagonBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypehexagonBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypestarBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypestarBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypestarBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypewallBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypewallBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypewallBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypeequilateralBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypeequilateralBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypeequilateralBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypetriangleBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypetriangleBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypetriangleBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypecircleBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypecircleBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypecircleBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypeellipsoidBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypeellipsoidBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypeellipsoidBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypesquareBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypesquareBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypesquareBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTyperoundedBoxBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTyperoundedBoxBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTyperoundedBoxBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypehexagonBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypehexagonBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypehexagonBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypestarBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypestarBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypestarBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/obstacleTypewallBottom_offsetX0.0.json
python run_sweep.py sweeps/dambreak/obstacleTypewallBottom_offsetX0.5.json
python run_sweep.py sweeps/dambreak/obstacleTypewallBottom_offsetX1.0.json
python run_sweep.py sweeps/dambreak/noObstacle_fillRatio0.333.json
python run_sweep.py sweeps/dambreak/noObstacle_fillRatio0.5.json
python run_sweep.py sweeps/dambreak/noObstacle_fillRatio0.667.json
