python run_sweep.py sweeps/impact/shapecircle_impactAngle0.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shapecircle_impactAngle0.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shapecircle_impactAngle15.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shapecircle_impactAngle15.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shapecircle_impactAngle30.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shapecircle_impactAngle30.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shapebox_impactAngle0.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shapebox_impactAngle0.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shapebox_impactAngle15.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shapebox_impactAngle15.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shapebox_impactAngle30.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shapebox_impactAngle30.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shaperoundedBox_impactAngle0.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shaperoundedBox_impactAngle0.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shaperoundedBox_impactAngle15.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shaperoundedBox_impactAngle15.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shaperoundedBox_impactAngle30.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shaperoundedBox_impactAngle30.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shapehexagon_impactAngle0.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shapehexagon_impactAngle0.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shapehexagon_impactAngle15.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shapehexagon_impactAngle15.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shapehexagon_impactAngle30.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shapehexagon_impactAngle30.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shapestar5_impactAngle0.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shapestar5_impactAngle0.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shapestar5_impactAngle15.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shapestar5_impactAngle15.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shapestar5_impactAngle30.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shapestar5_impactAngle30.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shapetriangleIsosceles_impactAngle0.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shapetriangleIsosceles_impactAngle0.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shapetriangleIsosceles_impactAngle15.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shapetriangleIsosceles_impactAngle15.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shapetriangleIsosceles_impactAngle30.0_lateralOffset0.0.json
python run_sweep.py sweeps/impact/shapetriangleIsosceles_impactAngle30.0_lateralOffset0.2.json
python run_sweep.py sweeps/impact/shapecircle_nBodies3.json
python run_sweep.py sweeps/impact/shapecircle_nBodies4.json
python run_sweep.py sweeps/impact/shapecircle_nBodies5.json
python run_sweep.py sweeps/impact/shapebox_nBodies3.json
python run_sweep.py sweeps/impact/shapebox_nBodies4.json
python run_sweep.py sweeps/impact/shapebox_nBodies5.json
python run_sweep.py sweeps/impact/shaperoundedBox_nBodies3.json
python run_sweep.py sweeps/impact/shaperoundedBox_nBodies4.json
python run_sweep.py sweeps/impact/shaperoundedBox_nBodies5.json
python run_sweep.py sweeps/impact/shapehexagon_nBodies3.json
python run_sweep.py sweeps/impact/shapehexagon_nBodies4.json
python run_sweep.py sweeps/impact/shapehexagon_nBodies5.json
python run_sweep.py sweeps/impact/shapestar5_nBodies3.json
python run_sweep.py sweeps/impact/shapestar5_nBodies4.json
python run_sweep.py sweeps/impact/shapestar5_nBodies5.json
python run_sweep.py sweeps/impact/shapetriangleIsosceles_nBodies3.json
python run_sweep.py sweeps/impact/shapetriangleIsosceles_nBodies4.json
python run_sweep.py sweeps/impact/shapetriangleIsosceles_nBodies5.json
