python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 1 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 1 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 1 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 1 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 1 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 1 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 1 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 1 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 2 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 2 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 2 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 2 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 2 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 2 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 2 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 2 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 4 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 4 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 4 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 4 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 4 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 4 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 4 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 4 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 1 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 1 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 1 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 1 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 1 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 1 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 1 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 1 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 2 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 2 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 2 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 2 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 2 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 2 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 2 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 2 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 4 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 4 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 4 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 4 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 4 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 4 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 4 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 4 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 1 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 1 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 1 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 1 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 1 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 1 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 1 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 1 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 2 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 2 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 2 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 2 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 2 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 2 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 2 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 2 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 4 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 4 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 4 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 4 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 4 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 4 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 4 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 4 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 1 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 1 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 1 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 1 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 1 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 1 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 1 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 1 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 2 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 2 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 2 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 2 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 2 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 2 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 2 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 2 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 4 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 4 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 4 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 4 --baseFrequency 1 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 4 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 4 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 4 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_wObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 4 --baseFrequency 2 --obstacleActive --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 1 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 1 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 1 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 1 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 1 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 1 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 1 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 1 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 2 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 2 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 2 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 2 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 2 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 2 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 2 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 2 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 4 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 4 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 4 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 4 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 4 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 4 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 4 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 3001897272 --octaves 4 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 1 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 1 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 1 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 1 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 1 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 1 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 1 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 1 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 2 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 2 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 2 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 2 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 2 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 2 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 2 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 2 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 4 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 4 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 4 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 4 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 4 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 4 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 4 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 398816462 --octaves 4 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 1 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 1 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 1 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 1 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 1 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 1 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 1 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 1 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 2 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 2 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 2 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 2 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 2 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 2 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 2 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 2 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 4 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 4 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 4 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 4 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 4 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 4 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 4 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 1784484113 --octaves 4 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 1 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 1 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 1 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 1 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 1 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 1 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 1 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 1 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 2 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 2 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 2 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 2 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 2 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 2 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 2 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 2 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 4 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 4 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 4 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 4 --baseFrequency 1  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 4 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 1 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 4 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 2 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 4 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 4 --noiseAmplitude 0.1
python generator.py --plot --tLimit 8.0 --obstacleType circleMiddle --offsetX 0.0 --W 2.0 --fillRatio 1.0 --fluidWidth 1.0  --maxExtent 0.4 --aoa 0 --caseName kolmogorov_noObstacle --nx 256 --targetDt 0.0002 --enableNoise --disableGravity --markerSize 8 --plotWidth 20 --seed 301484964 --octaves 4 --baseFrequency 2  --fullyPeriodic --enableKolmogorovForcing --kolmogorovForcingWavenumber 8 --noiseAmplitude 0.1
